apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhtap-chatbot-app-32
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/rhtap-chatbot-app-32:f314f0332589cf2703096289036d888433ecbe2d@sha256:b0859168a09210241aed992d50a40e1e1498cdd03c27abcf3c405b15dff33691
          name: container-image
